config/routes.rb
Rails.application.routes.draw do

root 'welcome#index'
  get '/search/:search' => 'search#index'
  get "/auth/twitter"
  get "/auth/:provider/callback" => "callbacks#index"

resources :users do
  resources :listings
end

resources :sessions, only: [:new, :create] do
  delete :destroy, on: :collection
end

resources :listings do
  resources :comments, only: [:create]
end

resources :abouts, only: [:index]
resources :feed_entries, only: [:index]

resources :faqs, only: [:index]
resources :contacts, only: [:index]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    can :manage, Listing do |x|
      x.user == user
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: :true 
end

app/models/feature.rb
class Feature < ActiveRecord::Base

  has_many :listings, through: :featurings
  has_many :featurings, dependent: :destroy
end

app/models/featuring.rb
class Featuring < ActiveRecord::Base
  
  belongs_to :listing
  belongs_to :feature
end

app/models/feed_entry.rb
class FeedEntry < ActiveRecord::Base

  geocoded_by :address
  after_validation :geocode
  mount_uploader :image_craigslist, ImageCraigslistUploader

def self.update_from_feed(url = "http://vancouver.craigslist.ca/search/apa?format=rss")
  feed = Feedjira::Feed.fetch_and_parse url
    feed.entries.first(30).each do |entry|
      address_entry = entry.title.scan(/\(([^\)]+)\)/).last
      # or .try(:first)
      address = address_entry ? address_entry.first : ""

      # byebug
      unless exists? guid: entry.id
          create!(
           title:                        entry[:title],
           description:                  entry[:summary],
           url:                          entry[:url],
           published_date:               entry[:published],
           guid:                         entry[:url],
           price:                        entry[:title],
           remote_image_craigslist_url:  entry[:img],
           address:                      address
           )
         end
       end
     end

def self.update_from_kijiji( url = "http://www.kijiji.ca/rss-srp-apartments-condos/vancouver/c37l1700287")

  feed = Feedjira::Feed.fetch_and_parse url
    feed.entries.first(30).each do |entry|
      unless exists? guid: entry.id
        create!(
        title:                          entry[:title],
        description:                    entry[:summary],
        url:                            entry[:url],
        published_date:                 entry[:published],
        guid:                           entry[:entry_id]
        )
      end
    end
  end

  def self.search(item)
    search_term = "%#{item}%"
    where(["title ILIKE :term  OR description ILIKE :term", {term: search_term}])
  end

end

app/models/listing.rb
class Listing < ActiveRecord::Base

  belongs_to :user

  has_many :features, through: :featurings
  has_many :featurings, dependent: :nullify
  has_many :comments, as: :commentable

  mount_uploader :image, ImageUploader

  geocoded_by :full_address
  after_validation :geocode

  validates :description, presence: true
  validates :address, presence: true



  def full_address
    "#{address}, #{city}, #{postal}, #{country}"
  end

  def self.search(item)
    search_term = "%#{item}%"
    where(["description ILIKE :term OR address ILIKE :term", {term: search_term}])
  end


end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :listings, dependent: :nullify

  validates :first_name ,presence: true
  validates :last_name  ,presence: true

  validates :email      , presence: true,
                          uniqueness: true,
                          format: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController

  def index
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to feed_entries_path, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def find_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def formatted_date(date)
    date.strftime("%Y-%b-%d")
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/feed_entries_helper.rb
module FeedEntriesHelper

  def feeds_json(feed)
    feeds_with_address = FeedEntry.where.not(longitude:nil, latitude: nil)
    Gmaps4rails.build_markers(feeds_with_address) do |feed, marker|
      marker.lat        feed.latitude
      marker.lng        feed.longitude
      marker.infowindow "<b>#{feed.title.truncate(20)}<b>"
    end
  end

end

app/helpers/feed_no_pics_helper.rb
module FeedNoPicsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper

    def listings_json(listings)
      listings_with_address = Listing.where.not(longitude:nil, latitude: nil)
      Gmaps4rails.build_markers(listings_with_address) do |listing, marker|
        marker.lat        listing.latitude
        marker.lng        listing.longitude
        marker.infowindow "<b>#{listing.description.truncate(20)}<b>"
      end
    end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rent Work</title>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Raleway:600' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render '/navbar/nav' %>
<%= yield %>





<script type="text/javascript">
  $('input[type="search"]')on("click", function(){
        $(this).val('');
  };

  window.addEventListener("scroll", function() {
  if (window.scrollY > 200) {
      $('#navbar').fadeOut();
  }
  else {
      $('#navbar').fadeIn();
  }
},false);

</script>

</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Welcome to Rent Work</title>
    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Raleway:600' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body id="homepage">
    <%= yield %>
  </body>
</html>

app/views/navbar/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top" id="navbar">
  <div class="container-fluid">
    <div class="navbar-header">
        <%= link_to root_path, class: "navbar-brand" do  %>
        <p id='brand'>Rent<i class="fa fa-home"></i><b>Works</b></p>
        <% end %>
    </div>
    <div class="container-fluid">
      <ul class="nav navbar-nav navbar-right" >
        <% if user_signed_in? %>
        <li>
          <p id="sign_in_name">
            Hi <%= current_user.first_name %> |
            <%= link_to "LIST", new_listing_path %> |
            <%= link_to "SIGN OUT", sessions_path, method: :delete %> |
          </p>
        </li>
            <% else %>
          <li id="sign_in"><%= link_to "SIGN IN", new_session_path %></li>
            <% end %>
        </ul>
    </div>
    <div class="clearfix" id="navbar2">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "HOME", root_path %></li>
        <li><a href="/abouts">ABOUT</a></li>
        <li><a href="/listings">LISTINGS</a></li>
        <li><a href="/feed_entries">WEB LISTINGS</a></li>
        <li><a href="/contacts">CONTACT US</a></li>
        <li><a href="/faqs">FAQ</a></li>
        <li><a href="/users/new">REGISTER</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right" id="searchbar">
        <li>
          <%= form_tag feed_entries_path, method: :get do %>
           <p>
             <%= search_field_tag :search, params[:search] %>
             <%= submit_tag "Search", name: nil, class: "btn btn-edit btn-sm" %>
           </p>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/navbar/_tabs.html.erb
<!-- Nav Panes -->
  <p id="notice"><%= notice %></p>
<ul class="nav nav-tabs">
  <!-- thumb nail  -->
  <li>
    <a href="/listings">Our Listings</a>
  </li>
  <li><a href="/feed_entries">Other Sources w/ Thumbnail</a></li>
  <li><a href="/feed_no_pics">Other Sources</a></li>
</ul>