config/routes.rb
Rails.application.routes.draw do

root 'welcome#index'
  get '/search/:search' => 'search#index'
  get "/auth/twitter"
  get "/auth/:provider/callback" => "callbacks#index"

resources :users do
  resources :listings
end

resources :sessions, only: [:new, :create] do
  delete :destroy, on: :collection
end

resources :listings do
  resources :comments, only: [:create]
end

resources :abouts, only: [:index]
resources :feed_entries, only: [:index]

resources :faqs, only: [:index]
resources :contacts, only: [:index]

end

app/models/listing.rb
class Listing < ActiveRecord::Base

  belongs_to :user

  has_many :features, through: :featurings
  has_many :featurings, dependent: :nullify
  has_many :comments, as: :commentable

  mount_uploader :image, ImageUploader

  geocoded_by :full_address
  after_validation :geocode

  validates :description, presence: true
  validates :address, presence: true



  def full_address
    "#{address}, #{city}, #{postal}, #{country}"
  end

  def self.search(item)
    search_term = "%#{item}%"
    where(["description ILIKE :term OR address ILIKE :term", {term: search_term}])
  end


end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :authorize!, only: [:edit, :update, :destroy]
  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
    # @listings = Listing.where.not(longitude: nil, latitude: nil)
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @comment = Comment.new
  end

  # GET /listings/new
  def new
    @listings     = current_user.listings
    @listing      = Listing.new
    @listing.user = current_user
    @features     = Feature.all
  end

  # GET /listings/1/edit
  def edit

  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    respond_to do |format|
      if @listing.save
        $client.update("Hi #{@listing.description}#{@listing.address} has been listed")
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.js { render :create_success }
      else
        format.html { render :new, notice: "Error" }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to new_listing_path, notice: 'Listing was successfully destroyed.' }
      format.js { render :create_failure }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit([:description, :address, :price, :postal, :city, :country, :image, :user_id, {feature_ids:[]}])
    end

    def authorize!
      redirect_to @listing, alert: "Access Denied" unless can? :manage, @listing
    end
end

app/helpers/listings_helper.rb
module ListingsHelper

    def listings_json(listings)
      listings_with_address = Listing.where.not(longitude:nil, latitude: nil)
      Gmaps4rails.build_markers(listings_with_address) do |listing, marker|
        marker.lat        listing.latitude
        marker.lng        listing.longitude
        marker.infowindow "<b>#{listing.description.truncate(20)}<b>"
      end
    end

end

app/views/listings/_current_listing.html.erb
<div class="container current_listings" id="<%= dom_id(listing) %>">
  <p>
    <h3><%= link_to listing.description, listing %></h3>
      <%= listing.address %>, Created at:
      <%= formatted_date(listing.created_at) %>
      <%= link_to "Delete", "/listings/#{listing.id}", method: :delete, class: "btn btn-danger btn-xs" %>
      <%= link_to 'Edit', edit_listing_path(listing.id), class: "btn btn-info btn-xs" %>

  </p>
</div>

app/views/listings/_form.html.erb
<%= simple_form_for (@listing||Listing.new) do |f| %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :price %>
  <%= f.input :postal %>
  <%= f.input :city %>
  <%= f.input :image %>
  <%= f.input :country, as: :select, collection: ActionView::Helpers::FormOptionsHelper::COUNTRIES  %>
  <%= f.association :features, as: :check_boxes %>
<%= f.submit "List", class: "btn btn-primary btn-sm" %>
<% end  %>

app/views/listings/create_failure.js.erb
$('#<%= dom_id(@listing) %>').fadeOut();

app/views/listings/create_success.js.erb
$('.panel-body.list_display').append("<%= j render 'current_listing', listing: @listing  %>")

<% @listing = Listing.new %>
$('.panel-body.list').replaceWith("<div class='panel-body list'><%= j render 'form' %><div>");

app/views/listings/edit.html.erb
<div class="container edit animated fadeIn">
  <div class="panel edit">
    <div class="panel-heading edit">
      Edit Listing <i class="fa fa-pencil"></i>
    </div>
    <div class="panel-body edit">
      <%= simple_form_for @listing do |f| %>
        <%= f.input :description %>
        <%= f.input :address %>
        <%= f.input :price %>
        <%= f.input :postal %>
        <%= f.input :city %>
        <%= f.input :image %>
        <%= f.input :country, as: :select, collection: ActionView::Helpers::FormOptionsHelper::COUNTRIES  %>
        <%= f.association :features, as: :check_boxes %>
      <%= f.submit "Update", class: "btn btn-primary btn-sm" %>
      <%= link_to 'Back', listings_path, class: "btn btn-warning btn-sm" %>
      <% end  %>
    </div>
  </div>
</div>

app/views/listings/index.html.erb
<div class="container animated fadeIn">

<div class="panel our_listings">

<div class="panel-heading out_listings">
    Listed <i class="fa fa-home"></i>
</div>
    <div id="map" style='width: 100%; height: 400px;'></div>
  </div>


  <div class="row">
        <% @listings.each do |listing| %>
    <div class="col-md-4 container animated fadIn">
      <div class="panel list_index">
        <div class="panel-heading list_index">
        </div>
        <div class="panel-body list_index pic">
         <%= image_tag listing.image, id:"index_pic" %>
        <div class="caption">
          <h3><%= listing.description %></h3>
            <p><small><%= listing.price %>
                      <%= listing.address %><br>
                      <%= listing.city %>, <%= listing.country %></small></p>
          <p><%= link_to "VIEW", listing, class: 'btn btn-info btn-sm' %></p>
        </div>
        </div>
      </div>
    </div>
          <% end %>
  </div>
</div>


  <script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%= raw listings_json(@listings).to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(11);
    });
  </script>

app/views/listings/new.html.erb
<div class="col-md-6 container list animated fadeIn">
  <div class="panel list">
    <div class="panel-heading list">
      <i class="fa fa-list"></i> List a Property
    </div>
    <div class="panel-body list">
      <%= render 'form' %>
    </div>
  </div>
</div>

<div class="col-md-6 container list_display">
  <div class="panel list_display">
    <div class="panel-heading list_display">
      Your Current Listings <i class="fa fa-book"></i>
    </div>
    <div class="panel-body list_display">
          <% @listings.each do |listing| %>
            <%= render "/listings/current_listing", listing: listing %>
            <hr>
          <% end %>

    </div>
  </div>
</div>

app/views/listings/show.html.erb
  <div class="col-md-6 container list_show animated fadeIn panel-group">
    <div class="panel-heading list_show">
      <i class="fa fa-map"> Views </i>
    </div>
    <div class="panel-body list_show">
      <div id="map" style='height: 400px;'></div>
    </div>
  </div>
</div>

<div class="col-md-6 panel-group container list_feature animated fadeIn" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel list_feature">
    <div class="panel-heading list_feature">
       <i class="fa fa-hand-o-down"></i> About the Listing 
    </div>
    <div class="panel-heading list_feature" role="tab" id="headingOne">
      <h4 class="panel-title list_feature">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
         Description
       </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body list_feature">
          <p><%= @listing.description %></p>
          <p><%= @listing.price %></p>
          <p><%= @listing.address %></p>
          <p><%= @listing.city %><%= @listing.country %></p>
        <div class="check_boxes">
          <% @listing.features.each do |x|%>
            <%= x.name %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="panel-body list_feature pic">
      <% if @listing.image.present? %>
        <%= image_tag @listing.image, id:"listing_pic"%>
      <% else %>
        <img src="/assets/default.gif">
      <% end %>
    </div>

<!-- <div class="col-md-6 container comment animated fadeIn"> -->
  <div class="panel-heading comment">
    <i class="fa fa-map"> Comments </i>
  </div>
  <div class="panel-body comment">

      <%= simple_form_for [@listing, @comment] do |f| %>
      <%= f.input :content, label: "Comment" %>
      <%= f.submit "Post", class: "btn btn-primary btn-sm" %>
      <% end %>

</div>


  <% @listing.comments.each do |comment| %>
  <div class="well">
    <p>"<%= comment.content %>"</p><br>
    <p>Date <%= formatted_date(comment.created_at) %></b><br>
  </div>
    <% end %>
</div>
<!-- </div> -->
  </div>
</div>


<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": <%= @listing.latitude %>,
      "lng": <%= @listing.longitude %>,
      "infowindow": "<%= @listing.address %>"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(15);
});
</script>